# Site settings
baseurl = "https://kikudai.com/"
languageCode = "ja"
title = "合同会社キクダイ | kikudai"
theme = "hugo-freelancer-theme"


[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# To provide some metadata for search engines feel free to add a few
	# information about you and your website.
	name = "合同会社キクダイ"
	description = "合同会社キクダイの自社ホームページ。"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
	#
	# What you need to do for the setup?
	#
	# - set your email address under 'email' below
	# - upload the generated site to your server
	# - send a dummy email youself to confirm your account
	# - click the confirm link in the email from www.formspree.io
	# - you're done. Happy mailing!
	email = "contact@kikudai.com"

	# Custom assets
	custom_css = ["./css/freelancer-kikudai.css"]
	custom_js  = ["//assets.tumblr.com/post.js"]

	[params.navigation]
		brand = "Kikudai"
    brandlogo = "./img/kikudai-logo.png"


	[params.header]
		# Copy your own image into './static/img/'' if you wish
		image = "kikudai.png"
		name = "Kikudai"
		subtitle = "人生の折り返し地点で、会社を設立するということ。"


	[params.concept]
		title = "大切にすること"
		# The about text is splitted into a left and right column
		left = "家庭（プライベート）、仕事、お金のバランスを考えること。"
		right = "ご近所、地域、ふるさとを考えた活動。"


	[params.news]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "お知らせ"

		[params.news.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttontext = "Close"


	[params.portfolio]
		# All projects defined in their own files. You can find example projects
		# at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
		# at the root of this Hugo site.
		# For more informtion take a look at the README.
		title = "仕事について"

		[params.portfolio.modal]
			client = "Client"
			date = "Date"
			category = "Category"
			buttontext = "Close"


	[params.contact]
		title = "お問い合わせ"

		# 'error' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "お名前"
			error = "Please enter your name."

		[params.contact.form.email]
			text = "メールアドレス"
			error = "Please enter your email address."

		[params.contact.form.phone]
			text = "TEL"
			error = "Please enter your phone number."

		[params.contact.form.message]
			text = "お問い合わせ内容"
			error = "Please enter a message."

		[params.contact.form.attention]
			text = "※入力していただいた個人情報は、お問い合わせ以外の目的で使用いたしません。 "

		[params.contact.form.button]
			text = "送信"


		[params.blog]
			title = "ブログ"
			leftimg = "./img/daichi-blog.png"
			leftlink = "http://blog.kikudai.com/"
			rightimg = "./img/sachico-blog.png"
			rightlink = "https://www.sachicodesign.com/"


		[params.footer.about]
			title = "会社について"
			etc = "設立 2016年6月"

		[params.footer.company]
			title = "合同会社キクダイ"
			president = "社長 菊池大地"

		[params.footer.location]
			title = "所在地"
			address = "東京都 日野市 豊田3"


	[params.footer]
		copyright = "Cloned [hugo-freelancer-theme](//github.com/digitalcraftsman/hugo-freelancer-theme). Powered by [Hugo](//gohugo.io).<br>(c)2016 Kikudai."

		[params.footer.credits]
			title = "About Freelancer"
			text = "Freelance is a free to use, open source Bootstrap theme created by [Start Bootstrap](//startbootstrap.com)."
