[build]
publish = "public"
command = "git submodule update -f --init && npm install -g postcss-cli && npm install autoprefixer && npm audit fix && hugo"

[build.environment]
HUGO_VERSION = "0.69.0"
HUGO_ENV = "production"
